### ISSUE TITLE
Encoding fails with 7200 x 3060 resolution

### ISSUE THREAD

**Issue by jossgray** [Vidvox/hap-qt-codec#20]
I'm trying to encode a movie to HAPQ which is 7200 x 3060. With MPEG-StreamClip the encoding fails with 'compression error'. It also fails in After Effects.

HAP is fine.

I have tried encoding from a PNG sequence and another HAPQ video.

**Comment by bangnoise** [comment]
Thanks for the report. I can reproduce this. The encoder is running out of memory - this should be avoidable, fix will follow.

**Comment by mkohler99** [comment]
I'm the one experiencing this Issue that Joss opened. Our artists are complaining that they are having trouble creating HAP or HAPQ files at this resolution, that Aftereffects fails to render the files. Is there any timeframe for this being fixed? Is there any more information I could provide that would help in the troubleshooting of this? Thanks so much!

**Comment by bangnoise** [comment]
I can't remember if AE has a setting to disable multi-threaded encoding - if so, disabling that will avoid the issue.

If you're in a hurry for a fix then drop me an e-mail - bangnoise@gmail.com

**Comment by n1ckfg** [comment]
I've also had trouble rendering large Hap movies out of AE CC 2013 and
2014...AE CC 2015 entirely revamped multithreading (all handled
automatically now, instead of user having to manually set number of threads
and RAM). Might be worth a test.

Nick

**Comment by bangnoise** [comment]
Tentative fix for this at https://github.com/Vidvox/hap-qt-codec/releases/tag/version-7-issue-20

**Comment by Sunsneezer** [comment]
I was having issues encoding to the relatively reasonable resolution of 3530 x 3052 from After Effects 2014 as well. My test outputs bleeted out 1-2 times out of 10 but always on the same frame in the same test batch, around 16-18. Using the secret setting to purge every frame out of 15 seemed to keep it in check but Version 7 fixed it completely! Thanks!

I'm noticing the render progress bar behaves very differently now, before it used to jump to frame 13 then stall then zip for a few frames then stall again etc. Now it's very steady and render time seems about 33% shorter but CPU usage is a lot higher is that right?

**Comment by bangnoise** [comment]
Thanks for the confirmation. Yep the difference is that rather than encoding several whole frames simultaneously, the codec now encodes (on several threads) each frame as it is delivered - so the progress bar no longer goes up in multiple frames. I'm surprised you see such an increase in render time, but 👍

**Comment by Sunsneezer** [comment]
I meant there is, with the machine I did the more tests on, i got a 33% *decrease* in render time! CPU usage feels like it increased by more than that though but I have no figure. Also, some computers (and our neighboring team) seemed immune to the crash but I never discovered why. Our park is very varied in hardware and OS but we all rub the same softwares.

**Comment by bangnoise** [comment]
oops sorry, typo, meant decrease

**Comment by bangnoise** [comment]
A new version, 8, which should be the next proper release if no issues emerge, is at https://github.com/Vidvox/hap-qt-codec/releases

This version fixes a problem encoding some odd-dimensioned frames which was introduced in release 7.
