### ISSUE TITLE
Small frame sizes outputs artifacts at the bottom of the frame

### ISSUE THREAD

**Issue by Sunsneezer** [Vidvox/hap-qt-codec#22]
Stumbled upon this one while generating proxies for the D3.
Here with a 400x400 sample
![400x400](https://cloud.githubusercontent.com/assets/14831792/10120654/6cdb365e-648c-11e5-99e5-2ac7d0fa74f0.PNG)

**Comment by bangnoise** [comment]
which version of the codec?

**Comment by Sunsneezer** [comment]
7

**Comment by bangnoise** [comment]
[Release 8](https://github.com/Vidvox/hap-qt-codec/releases/tag/version-8) has the fix for this
