### ISSUE TITLE
HAP Codec Release 7 breaks Quicktime Encoding in After Effect CC 2015

### ISSUE THREAD

**Issue by jossgray** [Vidvox/hap-qt-codec#23]
I've found that by installing release 7 of the HAP codec, all quicktime encoding (any codec) in after effects fails with the error;

"Rendering error while writing file "xxx". An output module failed. The file may be damaged or corrupted. (-1610153464)"

This does not happen with release 6.

AE 2015.0.1 release, version 13.5.1.48

This is on a macbook pro retina, 15 inch early 2015. Windows 10 64bit

**Comment by bangnoise** [comment]
Thanks for the report Joss. Unfortunately I can't recreate this issue on two machines here. Can you download the installer again, uninstall and then reinstall the codec, and confirm the issue still occurs. If so

Can you use the codec in QuickTime Player?
Can you check on another machine with Windows 10 and AE 2015 and duplicate the issue there?

**Comment by jossgray** [comment]
I haven't been able to reproduce so I'll close this.

**Comment by armonico8** [comment]
I have exactly this problem with version 7 and 8 but it works with version 6.
I can use the codec in QuickTime Player.
I don't have another machine to check right not.

![image](https://cloud.githubusercontent.com/assets/16422620/11990548/642e45f0-aa0f-11e5-9dd4-b44f6f87019e.png)

**Comment by Sunsneezer** [comment]
Do you use after effects multi-processing to render? If so try disabling it.

**Comment by armonico8** [comment]
Thanks for the answer.
I use After Effects CC2015 13.5 where this feature has been disabled :-(
http://blogs.adobe.com/aftereffects/2015/06/features-not-available-in-after-effects-cc-2015-13-5.html

**Comment by bangnoise** [comment]
@armonico8 
- have you uninstalled and re-installed version 8?
- can you confirm that all QT encoding in AE (not just Hap) fails for you, as in the original report for this issue?
- what version of Windows are you using?

**Comment by armonico8** [comment]
- yes, I uninstalled and re-installed version 8
- please excuse me. I'm wrong. My encodings fail only with Hap 7 and 8.
- I'm on a fresh windows 10 home edition

Thanks

**Comment by bangnoise** [comment]
@armonico8 This sounds like a different issue, I've opened #24 for it.
