### ISSUE TITLE
HAP q v8 crashes on export QuickTime 7.7.9 in Windows 7 x64

### ISSUE THREAD

**Issue by Nonikoff** [Vidvox/hap-qt-codec#27]
While exporting video from quicktime to Hap Q quicktime crashes. But to hap export is fine. Same when rendering from After Effects 2014.2 to hap Q Ae crashes

**Comment by bangnoise** [comment]
AE crashes or reports an error?

What are the dimensions of the movies you're encoding?

At what stage does the crash occur?

**Comment by Nonikoff** [comment]
1 on first render frame reports an error
After Effect error: Error (4) reading frame from file "file location"
(86::2) but file is ok and accessible 
2 Dimension is 5080x2950px

**Comment by bangnoise** [comment]
Can you try with a small movie (say 640x480, to remove all doubt), and see if you still get an error?

**Comment by bangnoise** [comment]
This should be fixed in the [latest release](https://github.com/Vidvox/hap-qt-codec/releases).
