### ISSUE TITLE
HAPQ v8 Crashes on Windows

### ISSUE THREAD

**Issue by tromerk** [Vidvox/hap-qt-codec#28]
I tried uninstalling/Reinstalling a few times.
Window 10 x64

HAP and HAP Alpha work fine.  But HAPQ fails in all programs I tried:
QuickTime Pro Export - Crashes quicktime the moment you select HAPQ as codec
Adobe Media Encoder: Fails - "Export Error. Error compiling movie. Unknown error."
After Effects: Hangs for 30 seconds after pressing render, then fails: "After Effects warning: logged one error -- "error: Error (4) reading frame from file "<filename>". (86 :: 2)"

File I am encoding is Quicktime Animation 100 - 1920x1080x30 and is confirmed good (works with all programs as well as works when making HAP and HAP Alpha).

Are you able to reproduce this issue?

Thanks,
kt

**Comment by bangnoise** [comment]
Thanks for the detailed report. Almost certainly duplicate #24 and #27 

Just to be clear, steps to reproduce this are

1. Open a 1920x1080x30 Animation codec movie in QuickTime Pro
2. File > Export > Hap Q
3. Observe crash when Hap Q is selected (presumably as it tries to render the preview)

?

**Comment by tromerk** [comment]
Yes.  To be more clear.

Load file in Quicktime
Export (CTRL-E)
Export: Movie to Quicktime Movie - **OPTIONS**
Video: Click **SETTINGS**
Compression Type Pulldown - select HAPQ
Quicktime Crashes immediately.  No message.

**Comment by bangnoise** [comment]
Thanks very much - should be fixed in [the new build I've just posted](https://github.com/Vidvox/hap-qt-codec/releases) - it would be good if you could verify it works for you

**Comment by tromerk** [comment]
I'll check now.  Stand bye.

**Comment by tromerk** [comment]
It works now.  Thanks!

I have some additional questions about color/encode quality (I'm getting better results from HAP than HAPQ).  Should I start a new thread or add on here?
Thanks!

**Comment by bangnoise** [comment]
Thanks for the confirmation, good to know - and for the detailed report to begin with.

Other questions to a new issue please.
