### ISSUE TITLE
Can't install HAP codec on Windows.

### ISSUE THREAD

**Issue by freaXtyle** [Vidvox/hap-qt-codec#30]
Hello!

I have a problem to install codec on my office PC. Installation stops with the massage "QuickTime for Windows must be installed to install the Hap QuickTime component". 
![screen](https://cloud.githubusercontent.com/assets/19385081/15284534/889df0fe-1b5a-11e6-8c44-08ee5c69308d.jpg)

Quicktime have been installed and then deleted and reinstalled but no luck. In your  source code there is a line next to this text with condition (I'm not a programmer) "<RegistrySearch Id='QTSystemRegistry' Type='directory' Root='HKLM' Key='SOFTWARE\Apple Computer, Inc.\QuickTime' Name='QTSysDir' Win64="no" />"
I searched my registry but there is no "Apple Computer, Inc." in 
HKEY_LOCAL_MACHINE\SOFTWARE\ 

"QuickTime 7.7.9 for Windows"
Windows 7 Professional.

Maybe there need to install different version of QT?

Best regards,
Alexander

**Comment by bangnoise** [comment]
The key will show up in regedit under SOFTWARE/Wow6432Node on 64-bit Windows. Is it there?

**Comment by freaXtyle** [comment]
Yes, here they are:
![image](https://cloud.githubusercontent.com/assets/19385081/15286607/a7017e1a-1b66-11e6-9e68-d75d06154e8d.png)

**Comment by bangnoise** [comment]
Does the directory at C:\Program Files (x86)\QuickTime\QTSystem\ exist?

**Comment by freaXtyle** [comment]
Yes:
![image](https://cloud.githubusercontent.com/assets/19385081/15287517/15a05882-1b6c-11e6-953c-960a6db0ebbd.png)

**Comment by bangnoise** [comment]
I suspect this is a user permissions issue, and that the user account doesn't have sufficient priveleges to read the key from the registry. If you are able to, try running the installer as an administrator.

Start Menu, type "command" and right click "Command Prompt", select "Run as Administrator"
type `msiexec /a C:\path\to\installer\HapQuickTimeCodec.Windows.v10.msi` and hit enter

**Comment by freaXtyle** [comment]
There is a error message:
![image](https://cloud.githubusercontent.com/assets/19385081/15290997/878f33f6-1b84-11e6-9cc7-ccb034685cab.png)

**Comment by freaXtyle** [comment]
maybe there is real permission problems? I can ask IT specialist of our company to try to install it remotly.

**Comment by bangnoise** [comment]
This does sound like a permissions problem.

Unfortunately the installer needs access to that registry value to determine the correct install location (it can vary with localisation).

We should try to detect this situation and give a useful error message.
