### ISSUE TITLE
HAP crash on encoding project with PNG32 sequence alpha

### ISSUE THREAD

**Issue by BertrandVillien** [Vidvox/hap-qt-codec#32]
We have a large project on Adobe Premiere Pro with a clip of PNG sequence in alpha (32 bits). This cause a crash on Adobe Media Encoder when encoding in HAP (tested from 60 to 75%) on a 30 seconds video.

We have transcoded the PNG sequence clip in HAP Alpha and the encoder does not crash anymore.

**Comment by bangnoise** [comment]
Which version of the codec?
OS X or Windows?
Can you give detailed step by step instructions to reproduce the crash?

**Comment by BertrandVillien** [comment]
OS 10.11 and Windows 10
HAP 8 to 11

In Premiere Pro :
Layer 1 : 30 sec PNG sequence in Alpha 32 bits
Layer 2 : 30 sec JPEG sequence
Media Encoder in HAP = Crash

Layer 1 : 30 sec PNG sequence transcoded to an HAP Alpha clip
Layer 2 : 30 sec JPEG sequence
Media Encoder in HAP = Pass

Dimensions : many configurations tested, from 2880 x 1080 to 9792 x 1080.

**Comment by BertrandVillien** [comment]
@bangnoise I've edited my last reply many times. Please check it online ;)

**Comment by BertrandVillien** [comment]
My bad ! We had several corrupted files in jpeg and png sequences.

Problem solved.

Sorry !
