### ISSUE TITLE
HAP Q Alpha Export from After Effects

### ISSUE THREAD

**Issue by jsaretz** [Vidvox/hap-qt-codec#33]
I got a problem with rendering a HAP Q Alpha directly from After Effects. The output module can't be set to render both RGB and Alpha at the same time - and so the rendered .mov does not have any information in the alphachannel stored.

![hap_q_alpha_ae_export](https://cloud.githubusercontent.com/assets/21010550/17644257/ca0355a8-6181-11e6-8360-e06966d69fbb.jpg)

Note: Everything works fine with the regular HAP Alpha.

Does anyone else have the same issue?

Setup: HAP v11, Windows 10, AE 2015.3 (also tested with AE 2014)

**Comment by bangnoise** [comment]
Thanks for the report - this should be fixed in the [latest release](https://github.com/Vidvox/hap-qt-codec/releases/latest). It would be great if you could confirm this works correctly for you.

**Comment by jsaretz** [comment]
Yes! v12 works as expected - thanks a lot!
