### ISSUE TITLE
Quicktime will not open HAP files without trying to convert

### ISSUE THREAD

**Issue by prophecy288** [Vidvox/hap-qt-codec#34]
Even with the Quicktime component installed, HAP files still don't want to open without converting. Is there some kind of player or workaround available? I've only been able to preview them in VDMX easily and I need to preview these to clients easily so they can be walked through the presentation.

I'm brand new to this codec but I also encountered major slowdown with render times. It was happening on a larger comp in AE CC, but seemed to do better with more bite size chunks.

**Comment by bangnoise** [comment]
The currently shipping QuickTime Player does not support non-Apple codecs. Use [QuickTime Player 7](https://support.apple.com/en-us/HT201288) or a third-party app.

I've just added a note to the README about that.
