### ISSUE TITLE
colour banding

### ISSUE THREAD

**Issue by fred-dev** [Vidvox/hap-qt-codec#35]
I get a lot of colour banding problems with HAP, it does not seem to matter which implementation, quicktime, DirectShow or avfoundation. I have used adobe media encoder, ffmpg and the avfoundation encoder to encode from a variety of sources and going to hap and hap q. No matter what I get ugly banding on subtle colour differences, I have some animated clouds that just never look good. Is this a known issue? Is there a work around, such as a 10 bit implementation? Or any tricks in encoding, I am at 100% quality all the time.

**Comment by Sunsneezer** [comment]
It is a known issue. I think it is because HAP has fixed low frequency
quantization. Adding noise or texture until banding breaks down is the only
thing that works for me.

**Comment by fred-dev** [comment]
Yes, the adding noise reduces it, but when I get passed content I often cannot mess with it. Does this mean it is permanent?

Is there a way to encode and decode HAP in 10 or 12 bit? This could be a way to get around it.

**Comment by bangnoise** [comment]
Sorry for the delay. 10-bit is something we're thinking about, but for Hap right now, yes banding on gradients is an issue.
