### ISSUE TITLE
FOURCC value for "Hap Q Alpha"?

### ISSUE THREAD

**Issue by LukasBanana** [Vidvox/hap-qt-codec#36]
Can anyone tell me the correct **FOURCC** value for **Hap Q Alpha**?

I'm only aware of these ones:
```
#define FOURCC_Hap1 MAKEFOURCC('H','a','p','1') // Hap
#define FOURCC_Hap5 MAKEFOURCC('H','a','p','5') // Hap Alpha
#define FOURCC_HapY MAKEFOURCC('H','a','p','Y') // Hap Q
/*                    ???                    */ // Hap Q Alpha
```

And by the way:
Where does the letter "Q" come from within the "Hap Q" and "Hap Q Alpha" names?
Hap Q has "YCoCg" color space for instance, so what does the "Q" mean in that context?
The nomenclature seems a little confusing to me.

**Comment by bangnoise** [comment]
````HapM```` - See the [specification](https://github.com/Vidvox/hap/blob/master/documentation/HapVideoDRAFT.md#names-and-identifiers).

Q is for quality.
