### ISSUE TITLE
Render times slow on 12 core vs 6 core mac pro

### ISSUE THREAD

**Issue by pbreisch** [Vidvox/hap-qt-codec#37]
I did a quick experiment on my last job with rendering on different machines.  

Project specs:
2245x1124 Hap9Alpha
rendered out of After Effects
We are requested to deliver Hap9 by our D3 operator, moving up to a newer build of HAP is not an option.

I rendered the exact same project from the same drives and experienced the following results:

6 Core Mac Pro/32GB RAM/D700 - 4 Min 55 Sec
12 Core Mac Pro/32 GB RAM/D700 - 34 Min 12 Sec
iMac 3.4i7/16GB RAM/AMD Radeon HD 6970M 1024 MB - 31min 31Sec

What I saw during the render was the processor usage varied greatly between the machines.  The 6 core was using 90% of all available processors at the same time while the imac and the 12 core was splitting the load up from one processor to another.  Is this a known issue or limitation of the codec? 

I've attached pics of the imac and 6 core render times.  These are direct compariosons, same files, same hard drives, etc.  I didn't snap a shot of the 12 core but it was very similar to the imac.

Thanks.

![img_2706](https://cloud.githubusercontent.com/assets/25083466/21897231/fad8e7c2-d8b6-11e6-821d-7406afbb83ec.jpg)
![img_2707](https://cloud.githubusercontent.com/assets/25083466/21897232/fad998ca-d8b6-11e6-85a9-f54f25d8c84b.jpg)

**Comment by bangnoise** [comment]
This is potentially an issue fixed since version 9. Are you able to test with the [latest](https://github.com/Vidvox/hap-qt-codec/releases/latest) release?

**Comment by pbreisch** [comment]
I am not. And we can only deliver with HAP9.

**Comment by bangnoise** [comment]
I don't know what reason your operator has for requiring version 9 (output should be identical), but I'd pursue upgrading the codec version with them as a first step.

**Comment by jossgray** [comment]
d3 has bundled v12 of the Quicktime codec in the installer for the last 5 months. AFAIK the only think that is not supported yet is YCoCg + Alpha.

**Comment by pbreisch** [comment]
That is interesting.  I have been consistently told to deliver Hap9 by all the operators I have worked with, the one thing they have in common is they are all from the same company.  I will run this up the chain and see where it gets me.  Thanks for the support.

**Comment by jossgray** [comment]
As @bangnoise mentioned there should be no binary difference between the output of different versions of the codec.

**Comment by bangnoise** [comment]
Closing this as it appears to be an issue fixed in recent versions.
