### ISSUE TITLE
Gradients making files huge and sometimes unreadable

### ISSUE THREAD

**Issue by maimframe** [Vidvox/hap-qt-codec#38]
Hello, after a lot of testing with various videos we noticed some movies with the same size would lead to very different encoding and playback results, after more test we discovered that the more gradient the input file has in a frame the harder it was to encode for hap, we are talking about a movie suddenly jumping to 1GB bitrate for a few frames in gradient intensive scenes and becoming unplayable because it is too demanding for the computer.

I could post an example file if needed. 

By gradient I mean smokes blowing above a rotating circle of earth with layered lightning above and flashes of lights. On the other hand a simple flag with the same resolution will encode easily and playback smoothly. Noise won't display this effect, only gradients, I can encode and easily play back a 10240x1080 file that is essentially moving fractal noise with transparent color bars and a moving line, but if I layed it with smoke and lights it becomes problematic.

It is worse if the movie is above HD, the ratio between frame with a decent bitrate and problematic one is greater.

Because of this we often have to segment our files or stretch them until the bitrate becomes acceptable in the problematic parts, we would like to avoid that of course.

Thanks for the otherwise awesome codec!

**Comment by bangnoise** [comment]
If you can provide an uncompressed frame (eg as a PNG), it's useful to have known problematic material - not sure there's much that can be done about it with Hap as it is now, but it's something to consider if we move to a different secondary compressor in the future.

**Comment by wwwerk** [comment]
I can demonstrate a 1080p h.264 MOV file, at 310 MB ballooning to 63 gigs following encoding to HapQ

Something is up here. PNG frames forthcoming.

**Comment by bangnoise** [comment]
Is this a dup of #47 or another issue?
