### ISSUE TITLE
AVF Batch Converter HAP quality slider does not affect file size

### ISSUE THREAD

**Issue by cansik** [Vidvox/hap-qt-codec#40]
Is it true that the HAP quality does not affect the file size? It should, as far as I understand. But I tried to convert some files today and it does not matter if I convert the files with 0% quality or 75% quality. The file size stays the same:

![image](https://user-images.githubusercontent.com/5220162/29389054-4bafd382-82e8-11e7-8c59-1c5cf0185989.png)

Is that a bug (or a feature)?

**Comment by bangnoise** [comment]
The quality slider affects the quality.

File size will differ only slightly. The main payoff is encoding speed (low quality is faster to encode).

This is explained in README.md.
