### ISSUE TITLE
HAP quicktime video flickering

### ISSUE THREAD

**Issue by alex5234** [Vidvox/hap-qt-codec#43]
Hello,

I have HAP videos I rendered at around 4k in size. When I play them back they look fine, but when I airplay them onto another monitor, the video starts to flicker. Also when I turn off the airplay, the video continues to flicker. It goes from darker video to brighter video.

Has anyone else experienced this? Is there a fix for this?

**Comment by bangnoise** [comment]
This is almost certainly a problem with whatever you are using for playback, not the Hap codec. Please seek support from the provider of your playback software, and re-open this issue and provide more info if you think there is an error with the Hap QuickTime Codec.
