### ISSUE TITLE
Bit depth and color in HAP?

### ISSUE THREAD

**Issue by smarrocco** [Vidvox/hap-qt-codec#44]
We are trying to determine the best data formats to output from edit systems for conversion to HAP and HAP/Q. What is the bit-depth (8.10.16?) of HAP & HAP/Q, and are they 422 or 444 with regards to color?

**Comment by bangnoise** [comment]
This QuickTime codec ingests 8-bit RGBA (4:4:4:4) with linear gamma

**Comment by smarrocco** [comment]
Thank you for the response. So is it safe to say that, for HAP (ignoring the alpha channel):
HAP = 8 bit, Linear, RGB (444) with higher compression and lesser quality.
and
HAPQ = 8 bit, Linear, RGB (444) with less compression and higher quality.

**Comment by bangnoise** [comment]
Yep
