### ISSUE TITLE
Adobe Discontinues Support of Quicktime 7 Era Codecs

### ISSUE THREAD

**Issue by mkohlerworldstage** [Vidvox/hap-qt-codec#46]
So It's finally happened. hap-qt-codec no longer works with the current version of the Adobe Creative Cloud Applications. 

https://helpx.adobe.com/x-productkb/multi/quicktime7-support-dropped.html

Is there a path forward using this plugin, or should we consider it abandoned and move on with rolling our own solution to this issue?

**Comment by PeterSchuebel** [comment]
Michael, not sure if that'll be any help in the short term, but my colleague Chet started this feature request to Adobe, and you can vote for it:
https://adobe-video.uservoice.com/forums/911311-after-effects/suggestions/33853372-support-the-hap-codec

**Comment by bangnoise** [comment]
Obviously quite a few people are affected by this. Parties interested in joining an effort for a prompt solution feel free to e-mail me - bangnoise@gmail.com. I'll update here once there is solid news to share.

**Comment by SourceChild** [comment]
I represent a company that performs over 12,000 large scale events per year, world wide.  Of those, more that 60% rely on using the HAP codec as the primary encoding option for playback.  While we have some options, losing HAP in Adobe video apps is going to become a catastrophic action.  My entire team is willing to help support actions to keep HAP as an active part of the total workflow.

**Comment by dlublin** [comment]
As Tom mentioned, there is lots of interest in coming up with a solution for this and one way or another it'll happen, reach out by email if you'd like to be part of that effort.

Beyond that, please be sure to vote on the Adobe user forums, as the ideal situation would be for them to add native support:
https://adobe-video.uservoice.com/forums/911311-after-effects/suggestions/33853372-support-the-hap-codec

**Comment by lrenkel1** [comment]
Absolutely agreed. The entertainment industry relies heavily on HAP and it is essential to our work flow.

**Comment by findersam** [comment]
Just chiming in to say I am interested in how all of this shakes out. Thanks Tom for all your work in HAP.

**Comment by jjm-3** [comment]
Hap has been vital in our large-format video show workflow for the last three years... We thank you or it and hope to continue using it in the future.

**Comment by bangnoise** [comment]
Happy to report that [disguise](https://www.disguise.one/) are working on an Adobe native exporter for Hap which will be open source and freely available. Work is in progress at the moment. Anyone keen to assist with the effort should get in touch with them.

**Comment by VuiMuich** [comment]
Is there any news on the implementation by disguise?
I started an attempt on the blackmagidesign forum for a feature request to get native support in DaVinci resolve, but my hope got destroyed relatively quick, as they stated HAP would not fit their target users blabla..
So a working solution in Adobe Media-Encoder would be greatly appreciated.

**Comment by fred-dev** [comment]
The discussion on the blackmagic website was interesting though, 

```
the underlying compression is from 1997. The only reason it isn't patent encumbered is that the patents expired.

I know interoperability is the goal, but Fusion and Generation support more modern texture compression technology and the image quality difference is huge. Why HAP doesn't support BC6h or BC7 or ATSC is just strange.
```
I dont mean to highjack the conversation, but what is the reason there is not BC7 support?

**Comment by bangnoise** [comment]
disguise's exporter for Adobe Premiere, Media Encoder, etc, is now released as an alpha.

https://github.com/disguise-one/hap-adobe-premiere-plugin/releases

**Comment by TroikaTronix** [comment]
It really seems clear to me that we need a simple movie container for HAP movies that is totally cross platform. I guess there are other non-GPL'd movie containers out there that could be used. But if we had some stable, cross-platform, open source code that would open such a container and deliver the frames in a timely (excuse the pun) fashion, we would all benefit because we a) would be using HAP which gives awesome performance and b) not be tied to the whims of Apple, Microsoft or any other corporate giant. I've been thinking about creating such a project for well over a year, but the coding demands of Isadora preclude me doing it on my own. Can we get a consortium together to do this for everyon's benefit? -- Mark Coniglio

**Comment by dlublin** [comment]
Hey Mark,

We've been talking about doing a group effort for the next major revision to the HAP spec along with general upkeep of related codebases, and general sort of planning along these lines; it isn't exactly a consortium, but drop me an email if you'd like to be part of this in some fashion.

**Comment by bangnoise** [comment]
Closing this as it's beyond the scope of this project - see the [disguise Hap exporter](https://github.com/disguise-one/hap-encoder-adobe-cc/releases) for Adobe CC
