### ISSUE TITLE
No Alpha Export

### ISSUE THREAD

**Issue by TreborKutscher** [Vidvox/hap-qt-codec#50]
Hello,

It seems there is no Alpha Channel exported in a composition containing alpha properties. Im Using hap+alpha. Also checked DXV3 codec with alpha on the same composition and it works.

I guess the problem is that the renderer isnt recognising that the codec/plugin is capable of alpha.
There is no checkbox wether rendering in 24bit or 32bit (32bit is the key). This means premiere streams no alpha information in the alphacapable codec -> every frame is 100% visible. 

are there any quick fixes?

**Comment by bangnoise** [comment]
Which version of Premiere? Can you confirm you are using this Hap QuickTime codec and not the [disguise Adobe plugin](https://github.com/disguise-one/hap-encoder-adobe-cc)?

**Comment by TreborKutscher** [comment]
I use Adobe Premiere CC 2017 V11

And yes you guessed right, i tried first the duisguise plugin. Was a test. After Choosing Quicktime as export and then the HAP-Alpha Codec it works fine.

But only works in CC2017 V11, in our production workstation with CC2019 and testwise CC2018 it dosnt do the trick.

And if you choose HAP-Q Alpha only 24bit is selecteble.

thanks a lot

**Comment by bangnoise** [comment]
QuickTime codecs are not supported by Adobe in CC2018+ so you will have to use the disguise plugin (or an alternative).

This issue in the disguise plugin is probably what you are hitting: disguise-one/hap-encoder-adobe-cc#25

Closing this as I don't think you have an issue with the QuickTime codec, which is what this project is. If I'm wrong please clarify your issue with the QuickTime codec.

**Comment by bangnoise** [comment]
> but can you check the HAP-Q + Alpha properties? 

In which exporter? This QuickTime codec or the disguise plugin?

**Comment by TreborKutscher** [comment]
in the quicktime exporter.  Format: Quicktime, Codec Hap Q Alpha

**Comment by bangnoise** [comment]
Please confirm you are on the [latest](
https://github.com/Vidvox/hap-qt-codec/releases/latest) (v12) version of the codec, as this sounds exactly like an issue fixed in that release.

**Comment by TreborKutscher** [comment]
Sorry you are right, i had them both dowbloaded an then installed the wrong version.

in v12  all works fine.

Issue solved,

a warm thank you

**Comment by bangnoise** [comment]
Great - hopefully the disguise exporter will be updated with a fix soon and you can transition to that plus latest CC.
