### ISSUE TITLE
Installed HAP into QT on Mac but does not show up in After Effects CC 2019 Render Output

### ISSUE THREAD

**Issue by ErKuehna** [Vidvox/hap-qt-codec#51]
Installed correctly into QuickTime library folder and AVF batch converter is able to render HAP movies from ProRes. Also playback works fine using Elmedia Player. The problem lies in both After Effects and Premiere Pro CC 2019 where HAP does not appear as a video compression option. While the AVF batch converter and Elmedia Player are viable solutions, I'm used to rendering directly out of After Effects and/or Premiere Pro. Is this something that has changed in CC 2019? Thanks and regards, Eric.

**Comment by bangnoise** [comment]
Adobe CC no longer supports third party QuickTime-based codecs. Use the [disguise encoder for Adobe CC](https://github.com/disguise-one/hap-encoder-adobe-cc/releases).

**Comment by ErKuehna** [comment]
Thanks for the info, Tom.
I’ll use the AVF batch converter and Elmedia player for now, as I have to deliver HAP renders to my client.

Eric Kuehnapfel
Post 2K, Inc.
design | edit | composite
________________
5 Algonquian Drive
Natick, MA 01760

Office: 508.647.0442
Cell: 508.259.3553

**Comment by bangnoise** [comment]
The disguise encoder linked above exports Hap directly from CC.
