### ISSUE TITLE
HAP direct export from after effects (and alpha in AME)

### ISSUE THREAD

**Issue by motwoozle** [Vidvox/hap-qt-codec#52]
hi, have installed codecs and CC plugin for mac, have tried on 2 os (high sierra and mojave)
and have tried in AE 19 and 20

no combination of these appers to allow direct export from AE, i have been able to export via AME 
and that seems ok,

i have another file to deliver with alpha, AME will not with any setting export the file with alpha,
has anyone else experienced the same?

any help warmly appreciated

**Comment by bangnoise** [comment]
This is the project for the original QuickTime codec, which is no longer supported.
The [disguise encoder](https://github.com/disguise-one/hap-encoder-adobe-cc/) supports direct export from AE.
