### ISSUE TITLE
Cannot see the hap export option

### ISSUE THREAD

**Issue by AtaB94** [Vidvox/hap-qt-codec#53]
Hello, I installed the latest hap-qt-codec. But I cannot find in any of my editing softwares. Am I missing something in the setup?
Thx in advance
Have a beautiful day.
Ata Bacanakgil

**Comment by bangnoise** [comment]
This is the original QuickTime codec - QuickTime is not supported by most software these days.

The Hap site lists some options - https://hap.video/integrations.html#encoding
