### ISSUE TITLE
Doesn't Work in Adobe / Apple Silicon

### ISSUE THREAD

**Issue by threedeeart** [Vidvox/hap-qt-codec#54]
Hello!

I have the new M1 Max Apple Silicon chip with MacOS Monterey. I cannot get the HAP codec to appear in Adobe Media Encoder natively. If I switch to Intel compatibility, it will appear. Historically, Apply only keeps the Rosetta compatibility for a short period of time, so this workaround will work for a couple versions only.

Thanks!

**Comment by VuiMuich** [comment]
Have you also checked [this](https://github.com/disguise-one/hap-encoder-adobe-cc)?
Iirc the qt-encoder was only 32bit, so that's probably why it won't run on M1.

Idk if there is actually a plug-in that has a nativ M1 port, but it would definitely be nice to have some native M1-GPU support.

**Comment by ryderr** [comment]
i second this, cant seem to get it to install

**Comment by bangnoise** [comment]
This is the repo for the old QuickTime encoder, which is no longer supported.
